const RequestGroupDto = {
	created: null,
	createdDate: new Date(),
	createdName: "",
	description: "",
	id: null,
	isActive: true,
	isDelete: false,
	modified: null,
	modifiedDate: new Date(),
	modifiedName: "",
	numberRequest: 0,
	numberRequestData: 0,
	numberRequestType: 0,
	requestGroupCode: "",
	requestGroupName: "",
	tennant: null,
	tennantCode: "",
	tennantName: "",
};
export default RequestGroupDto;
