const FieldData = {
	id: null,
	fieldDataCode: "",
	fieldDataName: "",
	objectSchema: "",
	objectModel: "",
	created: null,
	option: "",
	description: "",
	nameOfField: "",
	fieldPattern: "",
	required: "",
	createdDate: new Date(),
	createdName: "",
	isActive: true,
	isDelete: false,
	modified: null,
	modifiedDate: new Date(),
	modifiedName: "",
	tennant: null,
	tennantCode: "",
	tennantName: "",
	field: null,
	formData: null,
	requestData: null,
	fieldInForm: null,
};
export default FieldData;
