const MailTemplateDto = {
	contentFile: "",
	content: "",
	footer: "",
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	description: "",
	createdRankName: "",
	id: null,
	isActive: true,
	isDelete: false,
	itemId365: "",
	mailTemplateCode: "",
	mailTemplateName: "",
	mappingInfo: "",
	modifiedDate: new Date(),
	modifiedName: "",
	pathFile: "",
	subject: "",
	receiverDefault: "",
	ccerDefault: "",
	bccerDefault: "",
};
export default MailTemplateDto;
