const OutgoingDocDto = {
	compendium: "",
	composeOrg: null,
	composeOrgAvatar: "",
	composeOrgName: "",
	createdDate: new Date(),
	createdName: "",
	creater: null,
	description: "",
	documentType: null,
	documentTypeCode: "",
	documentTypeName: "",
	finalScanDocName: "",
	id: null,
	intoOutgingBookDate: new Date(),
	isActive: true,
	isDelete: false,
	modifiedDate: new Date(),
	modifiedName: "",
	modifier: null,
	numberOfBook: "",
	oldStatus: 0,
	orgOwned: null,
	organizations: [],
	outgoingBook: null,
	outgoingBookCode: "",
	outgoingBookName: "",
	outgoingDocCode: "",
	outgoingDocName: "",
	outgoingDocNumber: "",
	outgoingDocStatus: null,
	outgoingStatusName: "",
	priorityCode: "",
	priorityLevel: null,
	priorityName: "",
	receiveOrgText: "",
	releaseDate: new Date(),
	releaseOrg: null,
	releaseOrgAvatar: "",
	releaseOrgName: "",
	securityCode: "",
	securityLevel: null,
	securityName: "",
	signAvatar: "",
	signDate: new Date(),
	signName: "",
	signer: null,
};
export default OutgoingDocDto;
