const TemplateFormDto = {
	attachmentFileDTOS: [],
	created: null,
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	description: "",
	fileExtension: "",
	fullPath: "",
	id: null,
	isActive: true,
	isDelete: false,
	mappingInfo: "",
	modified: null,
	modifiedDate: new Date(),
	modifiedName: "",
	ofice365Path: "",
	path: "",
	templateFormCode: "",
	templateFormName: "",
	tennant: null,
	tennantCode: "",
	tennantName: "",
	version: 0,
};
export default TemplateFormDto;
