const RequestDto = {
	created: null,
	createdDate: new Date(),
	createdName: "",
	description: "",
	directoryPath: "",
	form: null,
	id: null,
	isActive: true,
	isDelete: false,
	modified: null,
	modifiedDate: new Date(),
	modifiedName: "",
	numberRequestData: 0,
	processInfos: [],
	requestCode: "",
	requestGroup: null,
	requestName: "",
	requestType: null,
	templateForms: [],
	tennant: null,
	tennantCode: "",
	tennantName: "",
	ruleGenerateCode: [],
};
export default RequestDto;
