const IncomingDocDto = {
	comingDate: new Date(),
	compendium: "",
	createdDate: new Date(),
	createdName: "",
	creater: null,
	description: "",
	finalScanDocName: "",
	id: null,
	incomingBook: null,
	incomingBookCode: "",
	incomingBookName: "",
	incomingDocCode: "",
	incomingDocName: "",
	incomingDocNumber: "",
	incomingDocStatus: null,
	incomingDocType: null,
	incomingDocTypeCode: "",
	incomingDocTypeName: "",
	incomingStatusName: "",
	incommingDocDate: new Date(),
	intoIncomingBookDate: new Date(),
	intoOutgingBookDate: new Date(),
	isActive: true,
	isDelete: true,
	modifiedDate: new Date(),
	modifiedName: "",
	modifier: null,
	numberOfBook: "",
	oldStatus: 0,
	orgOwned: null,
	outOrganization: null,
	placeSendCode: "",
	placeSendName: "",
	priorityCode: "",
	priorityLevel: null,
	priorityName: "",
	securityCode: "",
	securityLevel: null,
	securityName: "",
};
export default IncomingDocDto;
