const ManageStampInfoDto = {
	content: "",
	copiesNumber: 0,
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	creater: null,
	expiredDateReturn: null,
	id: null,
	isActive: true,
	isDelete: true,
	modifiedDate: new Date(),
	modifiedName: "",
	modifier: null,
	orgReturn: null,
	orgReturnName: "string",
	orgStorage: null,
	requestData: null,
	returnDate: null,
	stamp: null,
	stampCode: "",
	stampDate: null,
	stampName: "",
	stamperName: "",
	status: "",
	storageCode: "",
	storageLocation: "",
	storagePosition: "",
};
export default ManageStampInfoDto;
