const AttachmentFileDto = {
	created: null,
	createdDate: new Date(),
	createdName: "",
	description: "",
	fileExtension: "",
	fileName: "",
	fileType: null,
	fullPath: "",
	id: null,
	idInFileService: "",
	incomingDoc: null,
	isActive: true,
	modified: null,
	modifiedDate: new Date(),
	modifiedName: "",
	ofice365Path: "",
	outgoingDoc: null,
	path: "",
	reqdataProcessHis: null,
	requestData: null,
	stepProcessDoc: null,
	templateForm: null,
	tennant: null,
	tennantCode: "",
	tennantName: "",
};
export default AttachmentFileDto;
